### ISSUE TITLE
1.19.2 issue with update von Ae2 /appliedenergistics2-forge-12.8.0-beta.jar  ? 

### ISSUE THREAD

**Issue by kevkev1604** [62832/MEGACells#11]
-- Head --
Thread: main
Stacktrace:
	at ninety.megacells.block.MEGAEnergyCellBlock.<init>(MEGAEnergyCellBlock.java:6) ~[megacells-1.3.1-1.19.2.jar%23207!/:1.3.1-1.19.2] {re:classloading}
-- MOD megacells --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.25.jar%23280!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.25.jar%23279!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /home/mcmod/mc/mods/megacells-1.3.1-1.19.2.jar
	Failure message: MEGA Cells (megacells) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.3.0-1.19.2
	Mod Issue URL: https://github.com/62832/MEGACells/issues
	Exception message: java.lang.NoSuchMethodError: appeng.block.networking.EnergyCellBlock: method 'void <init>()' not found
Stacktrace:
	at ninety.megacells.block.MEGAEnergyCellBlock.<init>(MEGAEnergyCellBlock.java:6) ~[megacells-1.3.1-1.19.2.jar%23207!/:1.3.1-1.19.2] {re:classloading}
	at ninety.megacells.block.MEGABlocks.block(MEGABlocks.java:68) ~[megacells-1.3.1-1.19.2.jar%23207!/:1.3.1-1.19.2] {re:classloading}
	at ninety.megacells.block.MEGABlocks.<clinit>(MEGABlocks.java:45) ~[megacells-1.3.1-1.19.2.jar%23207!/:1.3.1-1.19.2] {re:classloading}
	at ninety.megacells.MEGACells.<init>(MEGACells.java:42) ~[megacells-1.3.1-1.19.2.jar%23207!/:1.3.1-1.19.2] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.25.jar%23280!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.25.jar%23279!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

update von 10/9/2022
appliedenergistics2-forge-12.8.0-beta.jar

**Comment by 62832** [comment]
AE2 has only just been updated and I am still waiting for development builds to be available before I am actually able to update MEGA to support that version. This will be fixed very soon, just be patient.

**Comment by P3rf3ctXZer0** [comment]
Thanks now I don't need to say anything :)

**Comment by 62832** [comment]
Fixed in version 1.4.0 of MEGA.
